# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scriptname', models.CharField(max_length=100, verbose_name='\u811a\u672c\u540d\u79f0')),
                ('paramname', models.CharField(max_length=100, verbose_name='\u53c2\u6570\u540d\u79f0')),
                ('param', models.TextField(blank=True, verbose_name='\u53c2\u6570\u5217\u8868')),
            ],
        ),
    ]
